# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WknFx_5k75cWm_vo-LjWizA4wXdszyRX
"""

import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
X = np.array([[0], [0.1], [0.3], [0.6], [0.8], [1.0]])
y = np.array([[0], [0], [0], [1], [1], [1]])  # 1 if input > 0.5

# Build the ANN model
model = Sequential()
model.add(Dense(4, input_dim=1, activation='relu'))  # Hidden layer with 4 neurons
model.add(Dense(1, activation='sigmoid'))            # Output layer

# Compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Train the model
model.fit(X, y, epochs=100, verbose=0)

# Test the model
test_input = np.array([[0.2], [0.4], [0.6], [0.9]])
predictions = model.predict(test_input)

# Display results
for i, pred in enumerate(predictions):
    print(f"Input: {test_input[i][0]}, Prediction: {pred[0]:.2f}")
  # 1.5567888->1.55