# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WknFx_5k75cWm_vo-LjWizA4wXdszyRX
"""

import numpy as np
import matplotlib.pyplot as plt
fig, axs = plt.subplots(2, 2)

axs[0, 0].plot([1, 2, 3], [1, 4, 9])
axs[0, 0].set_title('Plot 1')

axs[0, 1].bar(['A', 'B', 'C'], [5, 7, 3])
axs[0, 1].set_title('Plot 2')

axs[1, 0].scatter([1, 2, 3], [9, 4, 1])
axs[1, 0].set_title('Plot 3')

axs[1, 1].hist(np.random.randn(100), bins=10)
axs[1, 1].set_title('Plot 4')

plt.tight_layout()
plt.show()