# -*- coding: utf-8 -*-
"""Day4_Pandas_HandsOn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iA6DyXulhNxDJfJtoVmgXe-EsNqm-Krt

## 🐼 Day 4: Pandas Hands-On (Student Version)
Write your code in the cells below each instruction.

### Slide 2–3: Series Object
💡 **Task:** Write code to demonstrate this concept based on what was shown in the slide.
"""

import pandas as pd
names = ['Balaji', 'Ramesh']
s = pd.Series(names, index = ['R', 'M'])
s['M']

# Create a dictionary with countries as keys and
# value as their capitals corresponding

countries = {'India' : 'New Delhi', 'America' : 'Washington DC', 'UK' : 'London'}
countries_series = pd.Series(countries)
countries_series['India']

import pandas as pd

marks1 = pd.Series([80, 32, 50])
marks2 = pd.Series([60, 50,79])

final_marks = pd.concat([marks1, marks2], ignore_index=True)
final_marks

import pandas as pd

dict1 = {'MI': 5, 'CSK': 5}
dict2 = {'RCB': 0, 'SRH': 2}

series1 = pd.Series(dict1)
series2 = pd.Series(dict2)

series3 = pd.concat([series1, series2])
sorted_series = series3.sort_values(ascending=True)
print(sorted_series)

"""### Slide 5–6: DataFrame from Dictionary
💡 **Task:** Write code to demonstrate this concept based on what was shown in the slide.
"""

data = {'Name': ['Alice', 'Bob'], 'Age': [25, 30]}
df = pd.DataFrame(data)
print(df)

"""### Slide 7: DataFrame from List of Lists
💡 **Task:** Write code to demonstrate this concept based on what was shown in the slide.
"""

array = [[1,2], [3, 4]]
df = pd.DataFrame(array, columns=['A', 'B'], index = ['row_1', 'row_2'])
print(df)

"""### Slide 9: DataFrame from Series
💡 **Task:** Write code to demonstrate this concept based on what was shown in the slide.
"""

# Your code here

"""### Slide 10: Reading a CSV
💡 **Task:** Write code to demonstrate this concept based on what was shown in the slide.
"""

df = pd.read_csv('/content/Iris.csv')
df.head()

df.drop(df.columns[0], axis=1, inplace=True)
df.head()

df.head(10)

df.shape

df.info()
df.describe()

df.isnull().sum()

df.duplicated().sum()

df.drop_duplicates(inplace=True)



"""# Hands on practice

"""

import pandas as pd
df = pd.read_csv('/content/Data.csv')
df

df = df.dropna()
df.reset_index(drop = True, inplace = True)
df['city'] = ['a', 'b', 'c', 'a', 'b', 'c', 'a', 'b']
df

# 2 types of indexing in pandas dataframe
# loc vs iloc

df.loc[2, 'Country']  # 'Germany'
df.iloc[:, :3]

# df.drop('Age', axis = 1, inplace=True)
# df
# df.drop(0, axis=0, inplace=True)
df.reset_index(drop=True, inplace=True)
df

"""### Slide 11: Index, Columns, Values
💡 **Task:** Write code to demonstrate this concept based on what was shown in the slide.
"""

# Your code here

"""### Slide 12: Add/Drop Columns
💡 **Task:** Write code to demonstrate this concept based on what was shown in the slide.
"""

# Your code here

"""### Slide 13: Copy vs View
💡 **Task:** Write code to demonstrate this concept based on what was shown in the slide.
"""

# Your code here

"""### Slide 14: iloc vs loc
💡 **Task:** Write code to demonstrate this concept based on what was shown in the slide.
"""

# Your code here

"""### Slide 16: Drop Rows/Columns
💡 **Task:** Write code to demonstrate this concept based on what was shown in the slide.
"""

# Your code here

"""### Slide 18–19: Handling NaNs
💡 **Task:** Write code to demonstrate this concept based on what was shown in the slide.
"""

# Your code here

"""### Slide 22: Boolean Indexing
💡 **Task:** Write code to demonstrate this concept based on what was shown in the slide.
"""

# Your code here

"""### Slide 25: groupby()
💡 **Task:** Write code to demonstrate this concept based on what was shown in the slide.
"""

# Your code here